name: Frontend-Lint
on:
  pull_request:
    branches: [ main ]
    paths:
      - 'config-ui/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache Frontend-Lint
      id: cache-Frontend-Lint
      uses: actions/cache@v3
      with:
        path: Frontend-Lint
        key: ${{ runner.os }}-Frontend-Lint
    - name: Install modules
      run: cd config-ui; npm i
    - name: Run ESLint
      run: cd config-ui; npm run lint
